
@api = http://localhost:4000/acceso


GET {{api}}

###

GET {{api}}/2

###
POST {{api}}

Content-Type: application/json

{
    
    "id_user": "1",
    "token": "dadadjkndkenekhsdksdfsf506464608461630adadadsaas"
}

###
DELETE  {{api}}/1

###
PUT {{api}}/2
Content-Type: application/json

{
    "name_rol": "Admin",
    "estado": "N"
}