name: Build and Test PR to Stagging

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Installation of Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install --no-audit --no-fund --no-optional
      - name: Testing Linter
      - run: npm eslint
      - name: Testing Build
      - run: npm run build --if-present
