name: Build and Test PR to Stagging

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          fetch-depth: 0
          node-version: ${{ matrix.node-version }}
      - name: Installation of Node.js ${{ matrix.node-version }}
        run: cd cliente npm install --no-audit --no-fund --no-optional --force
      - name: Testing Linter
        run: npm eslint
      - name: Testing Build
        run: npm run build --if-present
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test
  